/** @type {import('tailwindcss').Config} */
export default {
            darkMode: "class",
            content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
                extend: {
                    "colors": {
                        "on-tertiary-fixed": "#042014",
                        "surface-tint": "#b8c4ff",
                        "surface-bright": "#37393e",
                        "on-primary-container": "#a8b8ff",
                        "surface-dim": "#111318",
                        "inverse-primary": "#3755c3",
                        "inverse-surface": "#e2e2e8",
                        "surface": "#111318",
                        "on-error": "#690005",
                        "surface-container-lowest": "#0c0e12",
                        "on-surface-variant": "#c4c5d5",
                        "on-secondary-fixed-variant": "#005049",
                        "primary-fixed-dim": "#b8c4ff",
                        "on-secondary-container": "#00302b",
                        "secondary-fixed": "#89f5e7",
                        "secondary-container": "#29a195",
                        "data-teal": "#2DD4BF",
                        "surface-card": "#161B22",
                        "on-primary": "#002584",
                        "on-secondary-fixed": "#00201d",
                        "tertiary-fixed": "#caead6",
                        "on-tertiary": "#1b3628",
                        "on-error-container": "#ffdad6",
                        "surface-border": "#30363D",
                        "on-surface": "#e2e2e8",
                        "on-tertiary-container": "#a4c3af",
                        "inverse-on-surface": "#2f3035",
                        "primary-fixed": "#dde1ff",
                        "surface-container-highest": "#333539",
                        "on-primary-fixed-variant": "#173bab",
                        "secondary": "#6bd8cb",
                        "data-indigo": "#6366F1",
                        "outline": "#8e909f",
                        "on-primary-fixed": "#001453",
                        "surface-container-high": "#282a2e",
                        "background": "#111318",
                        "surface-container-low": "#1a1c20",
                        "secondary-fixed-dim": "#6bd8cb",
                        "tertiary": "#afceba",
                        "tertiary-fixed-dim": "#afceba",
                        "on-tertiary-fixed-variant": "#314d3e",
                        "error": "#ffb4ab",
                        "error-container": "#93000a",
                        "surface-variant": "#333539",
                        "on-background": "#e2e2e8",
                        "primary-container": "#1e40af",
                        "outline-variant": "#444653",
                        "tertiary-container": "#355142",
                        "surface-container": "#1e2024",
                        "primary": "#b8c4ff",
                        "on-secondary": "#003732"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "spacing": {
                        "gutter": "24px",
                        "margin-desktop": "40px",
                        "container-max": "1440px",
                        "base": "8px",
                        "margin-mobile": "16px"
                    },
                    "fontFamily": {
                        "display-lg": ["Nunito"],
                        "headline-lg": ["Nunito"],
                        "label-sm": ["Nunito"],
                        "body-md": ["Nunito"],
                        "label-md": ["Nunito"],
                        "headline-md": ["Nunito"],
                        "body-lg": ["Nunito"],
                        "headline-lg-mobile": ["Nunito"]
                    },
                    "fontSize": {
                        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}]
                    }
                },
            },
        }
